### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [ericelliott/qconf#16]
Hello world?
----------
Hello there. You may ( or may not ) recognize me as one of the many people that likes following your blog and that recently got a hold on your JS book.

Yes yes, I know what you will say "the book is outdated and such" ( it is what you told me last time at least :P ), but I still read it anyway because I enjoyed it and because I think there are some pearls there that I can learn from. 

Yeah yeah, so what do you want?
------------
`qconf` was one of them. I have been battling on how to develop apps following the [12-factor app standard]( https://12factor.net/config ) ( I won't bore you with the details ) and I need something simple to check files and ENV variables. 

Problem
-----------
So I installed this library in my project, created a `config.env` file with the following json:
```
{
    "VAR_TEST": 1
}

```
and run the following code: `var qconf = require("qconf"), config = qconf(["./config.env"]);`

And it blew up:

> TypeError: Parameter "url" must be a string, not undefined
>     at Url.parse (url.js:81:11)
>     at urlParse (url.js:75:5)
>     at Object.loadSource (/home/service/testLogs/node_modules/qconf/lib/load-source.js:34:9)
>     at /home/service/testLogs/node_modules/qconf/lib/process-dependencies.js:84:29
>     at Array.map (native)
>     at processDependencies (/home/service/testLogs/node_modules/qconf/lib/process-dependencies.js:44:31)
>     at configure (/home/service/testLogs/node_modules/qconf/qconf.js:59:7)
>     at repl:1:40
>     at ContextifyScript.Script.runInThisContext (vm.js:23:33)
>     at REPLServer.defaultEval (repl.js:339:29)
> > var qconf = require("qconf"), config = qconf(["file://config.env"]);
> TypeError: Parameter "url" must be a string, not undefined
>     at Url.parse (url.js:81:11)
>     at urlParse (url.js:75:5)
>     at Object.loadSource (/home/service/testLogs/node_modules/qconf/lib/load-source.js:34:9)
>     at /home/service/testLogs/node_modules/qconf/lib/process-dependencies.js:84:29
>     at Array.map (native)
>     at processDependencies (/home/service/testLogs/node_modules/qconf/lib/process-dependencies.js:44:31)
>     at configure (/home/service/testLogs/node_modules/qconf/qconf.js:59:7)
>     at repl:1:40
>     at ContextifyScript.Script.runInThisContext (vm.js:23:33)
>     at REPLServer.defaultEval (repl.js:339:29)

Questions, questions....
-------------

Now, I read the documentation at least 3 times but I couldn't find anything related to URLs nor any of the like. It could be that I am not using the library as I should, but if that's not the case and this is in fact an unexpected behavior, could I expect a fix?

Is this project still being maintained/alive? 

If not, which similar projects would you recommend?

**Comment by ericelliott** [comment]
qconf uses strings in URL format, not OS file path format, in order to support loading in a variety of ways. Try `qconf(["file://config.env"]);`.

**Comment by ericelliott** [comment]
After deeper investigation, it looks like even with the correct string input, this will fail. There must have been a breaking change in the Node APIs since the last version was published. Would you like to update it and make a pull request?

**Comment by Fl4m3Ph03n1x** [comment]
I will see what I can do on my spare time, but unfortunately I can't make any promises. 
Will try to prioritize this over my projects and see what I can do!

**Comment by Fl4m3Ph03n1x** [comment]
So, I have messed a little with the code I have I found something. 

Test that fails:

```
test('multifile path override, as first argument', function (t) {
  config = qconf(
    ['file://test/path-override.json', 'file://config/config.json']); //KABOOM

  t.ok(config.get('default_setting'),
    'should read configuration from custom paths from in passed array.');
  t.equal(config.get('path_override'), false,
    'path_override should be false.');
  t.end();
});
```

This test fails with the error I described before.

Problematic code in `qconf.js` line 59:

```
// If the first argument is an Array,
    // assume that it is a list of dependencies.
    if ( Array.isArray(overrides) ) {
      processDependencies(providers, dependencies)
```

The issue here, is that `processDependencies` expects the second parameter `dependencies` to be an Array of Objects instead of an Array of Strings, which is what we are passing ( ['file://test/path-override.json', 'file://config/config.json']) )

The objects are expected to have the format: 

```
{
    name: String
    source: String
    dependencies: [] //optional
}
```

Because `processDependencies` tries to access these properties ( which strings don't have ), it gets and passes undefined down the line which ends up blowing up.

This whole thing happens because in `function configure(overrides, URIs)` ( line 30) the first parameter is an array.

Now, it is not clear to me if this is actual intended behavior and the docs just need updating ( instead of passing an array of Strings, one could pass an array of objects with the given format ) or if I am missing something else that to you will be quite obvious. 

The one thing I took from here, is that, at least to me, it doesn't appear to be an API breaking change from Node.js.

What do you think?

**Comment by ericelliott** [comment]
That is possible. What happens if you roll back to the previous version?

**Comment by ericelliott** [comment]
Thanks for the investigation.
